services:
  - type: web
    name: devcore-backend
    runtime: node
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://devcore_user:U7JgJOZDty1TIVQtoVq4Xa5JwYh7vQLG@dpg-d56091ngi27c73drvfq0-a.oregon-postgres.render.com/devcore?sslmode=require&connection_limit=5&pool_timeout=10
      - key: DIRECT_DATABASE_URL
        value: postgresql://devcore_user:U7JgJOZDty1TIVQtoVq4Xa5JwYh7vQLG@dpg-d56091ngi27c73drvfq0-a.oregon-postgres.render.com/devcore?sslmode=require
    plan: free